__lime_hookfn --[[Lime]]
Regex.Match --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.SameLine --[[Kawaii]]
rconsolehide --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
debug.GetProtos --[[Eclipse]]
xi_listfiles_raw --[[Xinject]]
getconnectionthread --[[DeltaX]]
write_clipboard --[[Lime]]
oth.unhook --[[Kawaii, DeltaX]]
lz4decompress --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
is_fluxus_closure --[[Trigon, VegaX, ArceusX V5, CodeX]]
__lime_int_writefile --[[Lime]]
debug.setsafeenv --[[Kawaii]]
getcallingscript --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getallthreads --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
getdestroyedactors --[[DeltaX]]
get_hwid --[[Lime, Kawaii]]
Mouse1Click --[[Eclipse]]
getactorfromstate --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.Checkbox --[[Kawaii]]
request --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_checkcaller --[[Lime]]
xi_b64decode --[[Xinject]]
isluau --[[Kawaii]]
DrawingImmediate.Rectangle --[[Kawaii]]
replicateevent --[[Kawaii]]
ListFiles --[[Eclipse]]
delscript --[[Xinject]]
isourclosure --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
bit.bxor --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.tracerefs --[[ArceusX V5]]
deletefile --[[Trigon, VegaX, ArceusX V5, CodeX]]
gethiddengui --[[Kawaii, Eclipse]]
cache.compareinstances --[[Trigon, VegaX, ArceusX V5, CodeX]]
__kawaii_private_roots.FileDialogs.openfolderdialog --[[Kawaii]]
getreferences --[[Kawaii]]
websocket.Connect --[[FluxusZ, Kawaii]]
arceus.getcreationtime --[[Trigon]]
debug.setuntouched --[[Kawaii]]
voicechat.getcomchannel --[[Kawaii]]
getregistry --[[Trigon, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, CodeX]]
getinstancesofclass --[[Kawaii]]
get_comm_channel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
bit.byteswap --[[Eclipse, DeltaX]]
bit.bor --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getnilinstances --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
openfilesdialog --[[FluxusZ, Kawaii]]
CloseXinject --[[Xinject]]
cache.invalidate --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arcy.close --[[ArceusX V5]]
debug.resetmemorycategory --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_user_identifier --[[Kawaii]]
RakNet.OnPacketReceive.Wait --[[Kawaii]]
debug.getregistry --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getconstant --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Xinject.BuyAI --[[Xinject]]
game.HttpGet --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
syn_backup.unprotect_gui --[[Xinject]]
WriteScript --[[Xinject]]
syn.crypt.custom.encrypt --[[Kawaii]]
debug.isvalidlevel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
crypt.base64_encode --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_hidden_ui --[[Kawaii, Eclipse]]
consoleerror --[[Trigon, Xinject, VegaX, ArceusX V5, CodeX]]
debug.GetUpvalues --[[Eclipse]]
setconstant --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getconstants --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Drawing.clear --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
RakNet.receive --[[Kawaii]]
getsignalargumentsinfo --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
http.request --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_getgenv --[[Lime]]
KeyDown --[[Eclipse]]
getobjects --[[Kawaii, Eclipse, DeltaX]]
consoleprint --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
Signal.Destroy --[[Kawaii]]
DevConnect --[[VegaX]]
getscriptthread --[[Kawaii, DeltaX]]
arceus.show_toast --[[ArceusX]]
websocket.connect --[[FluxusZ, Kawaii, ArceusX V5, DeltaX]]
islineinfo --[[Trigon, VegaX, ArceusX V5, CodeX]]
syn.is_beta --[[Kawaii]]
os.time --[[Xinject]]
raknet.add_receive_hook --[[Trigon, VegaX, ArceusX V5, CodeX]]
keyrelease --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Xinject.OnlineLogout --[[Xinject]]
makewritable --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_int_delfile --[[Lime]]
Delta.version_num --[[DeltaX]]
debug.setproto --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
printconsole --[[Kawaii]]
Signal.DisconnectAll --[[Kawaii]]
debug.GetInfo --[[Eclipse]]
is_our_thread --[[Kawaii]]
syn_backup.protect_gui --[[Xinject]]
setstackhidden --[[Kawaii, DeltaX]]
get_destroyed_actors --[[DeltaX]]
savefiledialog --[[FluxusZ, Kawaii]]
get_fps_cap --[[Kawaii, Eclipse, DeltaX]]
raknet.buffer_to_string --[[Trigon, VegaX, ArceusX V5, CodeX]]
voicechat.setvolume --[[Kawaii]]
set_fps_cap --[[Kawaii, Eclipse, DeltaX]]
getconnection --[[Kawaii]]
pibble.gmail --[[DeltaX]]
__lime_debug_getcon --[[Lime]]
__lime_debug_getprotos --[[Lime]]
crypt.lz4.compress --[[Kawaii]]
xi_autoexec_read --[[Xinject]]
isluaconnection --[[DeltaX]]
MouseMoveRelative --[[Eclipse]]
InstanceTypeFilter.new --[[Kawaii]]
getrawmetatable --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
make_writable --[[Trigon, VegaX, Eclipse, ArceusX V5, CodeX]]
gethiddenprop --[[Kawaii]]
writescript --[[Xinject]]
setthreadcontext --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
online_logout --[[Xinject]]
rconsoleerror --[[Trigon, Xinject, VegaX, Kawaii, ArceusX V5, CodeX]]
Delta.is_vng --[[DeltaX]]
get_instances --[[Trigon, VegaX, Eclipse, ArceusX V5, CodeX]]
fire_touch_interest --[[Eclipse]]
is_secured_instance --[[Trigon, VegaX, ArceusX V5, CodeX]]
getthreadcontext --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
run_script --[[Xinject]]
Delta.is_ios --[[DeltaX]]
hex_decode --[[FluxusZ]]
loadstring --[[Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
on_actor_state_created.Wait --[[Kawaii]]
debug.GetConstant --[[Eclipse]]
__kawaii_private_roots.ImGuiMethods.SliderInt --[[Kawaii]]
arceus.WHWKIWIOSU --[[Trigon]]
__lime_props --[[Lime]]
rconsolename --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
synsaveinstance --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
getupvalue --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
report_user --[[Xinject]]
IsFile --[[Eclipse]]
voicechat.getstatus --[[Kawaii]]
_G.Spopup --[[Trigon]]
setupvalue --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
pibble.washington --[[DeltaX]]
hex_encode --[[FluxusZ]]
fire_signal --[[Eclipse]]
runcode --[[Trigon, VegaX, ArceusX V5, CodeX]]
GetGenv --[[Eclipse]]
dumpstring --[[Lime, Trigon, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
iswriteable --[[Trigon, VegaX, ArceusX V5, CodeX]]
__kawaii_private_roots.GetObjects --[[Kawaii]]
Mouse1Press --[[Eclipse]]
debug.setupvalue --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
consolewarn --[[Trigon, Xinject, VegaX, Kawaii, ArceusX V5, CodeX]]
loadfile --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
DelFolder --[[Eclipse]]
RakNet.OnPacketSend.Connect --[[Kawaii]]
arceus.delarceusfolder --[[Trigon]]
Xinject.OnlineUser --[[Xinject]]
is_synapse_function --[[Trigon, VegaX, ArceusX V5, CodeX]]
openfiledialog --[[FluxusZ, Kawaii]]
raknet.remove_receive_hook --[[ArceusX V5]]
checkcaller --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
syn.run_secure_function --[[Kawaii]]
setreadonly --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
ai_session_del_state --[[Xinject]]
arcy.console --[[ArceusX V5]]
RakNet.send --[[Kawaii]]
os.difftime --[[Xinject]]
json.format --[[Kawaii]]
unprotectgui --[[FluxusZ]]
Duration.FromNanoseconds --[[DeltaX]]
readbinarystring --[[DeltaX]]
consolehide --[[Kawaii]]
oth.is_hook_thread --[[Kawaii, DeltaX]]
Signal.Fire --[[Kawaii]]
mouse1release --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xinject.SetCurrentSuggestionScript --[[Xinject]]
hasmetatable --[[Kawaii]]
getthreadidentity --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
hookfunc --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
runonthread --[[Kawaii]]
get_calling_script --[[Trigon, VegaX, Eclipse, ArceusX V5, CodeX]]
WebSocket.connect --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Eclipse, ArceusX V5, DeltaX, CodeX]]
crypt.base64.encode --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
crypt.hex.decode --[[FluxusZ]]
gethwid_raw --[[Xinject]]
getfunctionbytecode --[[Kawaii, DeltaX]]
getRepo --[[FluxusZ]]
getfflagtype --[[Kawaii]]
ai_eco --[[Xinject]]
getrenvshared --[[Trigon, VegaX, ArceusX V5, CodeX]]
pibble.is_detected --[[DeltaX]]
json.minify --[[Kawaii]]
appendfile --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
cache.replace --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.setname --[[Kawaii]]
game.HttpPostAsync --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
comparefunctions --[[Kawaii]]
debug.setinfo --[[Kawaii, ArceusX V5]]
runteleportscripts --[[Xinject]]
cleardevconsole --[[Kawaii]]
cache.is_cached --[[Eclipse]]
os.date --[[Xinject]]
crypt.hexencode --[[FluxusZ]]
websocket.new --[[Kawaii]]
getclipboard --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Eclipse, ArceusX V5, CodeX]]
Delta.is_mac --[[DeltaX]]
syn.request --[[FluxusZ, Kawaii]]
fromclipboard --[[Trigon, VegaX, ArceusX V5, CodeX]]
json.validate --[[Kawaii]]
clear_teleport_queue --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
Clipboard.set --[[Kawaii]]
protectfunction --[[Trigon, VegaX, ArceusX V5, CodeX]]
consolecreate --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getexecutorname --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
rconsoleprint --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getallactors --[[DeltaX]]
crypt.base64_decode --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_getrenv --[[Lime]]
RakNet.OnPacketReceive.Once --[[Kawaii]]
xinject.SaveScript --[[Xinject]]
Delta.version --[[DeltaX]]
json.clone --[[Kawaii]]
Mouse1Release --[[Eclipse]]
__kawaii_private_roots.RakNetTransport --[[Kawaii]]
debug.getupvalues --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
GetProto --[[Eclipse]]
__lime_debug_getupval --[[Lime]]
isexecutorclosure --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
syn.is_cached --[[Kawaii]]
saveplace --[[Kawaii]]
__lime_loadstring --[[Lime]]
arceus.readarceusfile --[[Trigon]]
RakNet.addsendhook --[[Kawaii]]
json.getPath --[[Kawaii]]
AppendFile --[[Eclipse]]
rnet.is_enabled --[[DeltaX]]
QWIKEWJWOAZOAOSXKEUIEOWJMZAJZHNXKJCBUFOEN --[[Trigon, VegaX, ArceusX V5, CodeX]]
pibble.getpibbles --[[DeltaX]]
setname --[[Kawaii]]
isrenderobj --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.getreg --[[Kawaii]]
ai_sessions_state --[[Xinject]]
rconsoleerr --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
isvalidlevel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
restorefunction --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_debug_setupval --[[Lime]]
get_scripts --[[Trigon, VegaX, ArceusX V5, CodeX]]
loadtest --[[Xinject]]
executecode --[[Trigon, VegaX, ArceusX V5, CodeX]]
base64encode --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
actor.run_on_actor --[[Trigon, VegaX, ArceusX V5, CodeX]]
Input.LeftClick --[[Trigon, VegaX, ArceusX V5, CodeX]]
getsignal --[[Kawaii]]
arceus.writearceusfile --[[Trigon]]
xi_elevate --[[Xinject]]
listfolders --[[FluxusZ]]
is_delta_closure --[[DeltaX]]
XOS.close --[[Xinject]]
getfenv --[[Kawaii, DeltaX]]
infouiconsole --[[Trigon, VegaX, ArceusX V5, CodeX]]
bit.tobit --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
http.get --[[Xinject]]
get_deleted_actors --[[Kawaii, DeltaX]]
protectgui --[[FluxusZ]]
rconsolewrite --[[Kawaii]]
voicechat.stop --[[Kawaii]]
rLib.Start --[[Xinject]]
arceus.delarceusfile --[[Trigon]]
ishookedclosure --[[Xinject]]
crypt.decrypt --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
voicechat.play --[[Kawaii]]
syn.get_thread_identity --[[Kawaii]]
__lime_install_nc --[[Lime]]
__lime_ssdiag --[[Lime]]
xinject.AddTab --[[Xinject]]
Xinject.OnlineResume --[[Xinject]]
runfile --[[Kawaii]]
printdebug --[[Trigon, VegaX, ArceusX V5, CodeX]]
run_on_actor --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
writefileasync --[[Kawaii]]
__lime_int_dir --[[Lime]]
Xinject.AIBalance --[[Xinject]]
printuiconsole --[[Trigon, VegaX, ArceusX V5, CodeX]]
zstdcompress --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
syn.crypt.random --[[Kawaii]]
ai_buy_state --[[Xinject]]
RakNet.removesendhook --[[Kawaii]]
listfiles --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
crypt.generatebytes --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
CheckCaller --[[Eclipse]]
__kawaii_private_roots.ImGuiMethods.Button --[[Kawaii]]
require --[[Lime, Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, CodeX]]
getObjects --[[Eclipse]]
fireproximityprompt --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getpcdprop --[[Kawaii, DeltaX]]
getstateenv --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
crypt.zstd.decompress --[[Kawaii]]
Input.KeyUp --[[Trigon, VegaX, ArceusX V5, CodeX]]
readinternal --[[Xinject]]
debug.setupvaluename --[[Kawaii]]
lz4compress --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xinject.Settings.AddButton --[[Xinject]]
oth.get_root_callback --[[Kawaii, DeltaX]]
showModal --[[Xinject]]
Regex.Escape --[[Kawaii, DeltaX]]
GetObjects --[[Eclipse]]
fireclickdetector --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
MouseMoveRel --[[Eclipse]]
rconsolecreate --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
DrawingImmediate.FilledRectangle --[[Kawaii]]
imgui.create --[[Kawaii]]
rconsoleshow --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
setfenv --[[Kawaii]]
iswindowactive --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
set_hidden_property --[[Eclipse, DeltaX]]
is_fluxus_function --[[Trigon, VegaX, ArceusX V5, CodeX]]
detourfunction --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
RakNet.remove_receive_hook --[[Kawaii]]
bit.bnot --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getfflag --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
Xinject.AISessionDelete --[[Xinject]]
arceus.deletearceusfolder --[[Trigon]]
debug.getmetatable --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
GetGC --[[Eclipse]]
get_hidden_property --[[Eclipse]]
bit.countlz --[[Eclipse, DeltaX]]
setfflag --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getpid --[[Kawaii]]
actor.run --[[Trigon, VegaX, ArceusX V5, CodeX]]
gethiddenproperties --[[Kawaii, DeltaX]]
getspecialinfo --[[Kawaii]]
replacefunction --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
getallreplicatesignals --[[Trigon, VegaX, ArceusX V5, CodeX]]
arceus.UJSWOOALSKDSJEO --[[Trigon]]
set_normal_instance --[[Trigon, VegaX, ArceusX V5, CodeX]]
__lime_ws_close --[[Lime]]
__lime_int_isfile --[[Lime]]
crypt.random --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
on_actor_state_created.Once --[[Kawaii]]
voicechat.setspeed --[[Kawaii]]
getscriptenvs --[[Trigon, VegaX, ArceusX V5, CodeX]]
isconnectionenabled --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
isourcallstack --[[Trigon, VegaX, ArceusX V5, CodeX]]
MakeReadonly --[[Eclipse]]
bit.rshift --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Duration.FromMicroseconds --[[DeltaX]]
crypt.encode --[[Xinject]]
create_comm_channel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
Xinject.IsOnline --[[Xinject]]
Regex.Replace --[[Kawaii]]
isclosure --[[Xinject]]
dump_string --[[Eclipse]]
__lime_ws_begin --[[Lime]]
crypt.hmac --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
__lime_boolfalse --[[Lime]]
set_readonly --[[Kawaii]]
__lime_ws_send --[[Lime]]
enableconnection --[[Trigon, VegaX, ArceusX V5, CodeX]]
Input.KeyDown --[[Trigon, VegaX, ArceusX V5, CodeX]]
GetRenv --[[Eclipse]]
clonefunc --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
os.getenv --[[Xinject]]
on_actor_state_created.Fire --[[Kawaii]]
logwarn --[[Trigon, VegaX, ArceusX V5, CodeX]]
getactors --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
Stopwatch.new --[[DeltaX]]
bit.replace --[[Eclipse, DeltaX]]
crypt.base64encode --[[Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
rconsoledestroy --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
arceus.crash --[[Trigon]]
DrawingImmediate.GetPaint --[[Kawaii]]
MakeFolder --[[Eclipse]]
ai_buy --[[Xinject]]
dumpbytecode --[[Kawaii, DeltaX]]
__kawaii_private_roots.ImGuiMethods.CollapsingHeader --[[Kawaii]]
getthreadscript --[[Trigon, VegaX, ArceusX V5, CodeX]]
save_instance --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
ai_state --[[Xinject]]
readfile --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getsynasset --[[Trigon, Xinject, VegaX, Kawaii, ArceusX V5, CodeX]]
gethui --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
hooksignal --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.SetUpvalue --[[Eclipse]]
bit.rol --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
raknet.clear_all_receive_hooks --[[Trigon, VegaX, ArceusX V5, CodeX]]
__lime_conn_walk --[[Lime]]
xi_genkey --[[Xinject]]
xinject.Settings.AddSwitch --[[Xinject]]
zstddecompress --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
ai_sessions --[[Xinject]]
get_script_hash --[[Eclipse]]
xi_lastcrash --[[Xinject]]
typeof --[[Kawaii]]
ai_session_del --[[Xinject]]
hex.decode --[[FluxusZ]]
getpcd --[[Kawaii, DeltaX]]
__lime_debug_getcons --[[Lime]]
RakNet.Send --[[Kawaii]]
_G.popup --[[Trigon]]
SJEIEWOWOQAPOAOAKSJM --[[Trigon, VegaX, ArceusX V5, CodeX]]
crypt.hexdecode --[[FluxusZ]]
rconsolewarn --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
restoreclosure --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
__lime_ws_free --[[Lime]]
__lime_debug_getproto --[[Lime]]
__lime_int_makefolder --[[Lime]]
debug.setmemorycategory --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
lz4_compress --[[DeltaX]]
clonereference --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
actor.isparallel --[[Trigon, VegaX, ArceusX V5, CodeX]]
get_callback_member --[[Eclipse]]
game.HttpGetAsync --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
getreg --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
clearqueueonteleport --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
zstd_decompress --[[DeltaX]]
HttpGetAsync --[[Xinject]]
__lime_fetch_poll --[[Lime]]
cleartpqueue --[[Kawaii]]
__lime_fetch_start --[[Lime]]
Delta.is_android --[[DeltaX]]
getbspval --[[Kawaii, DeltaX]]
crypt_base64decode --[[Lime]]
cansignalreplicate --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
json.decodeSafe --[[Kawaii]]
DrawingImmediate.Text --[[Kawaii]]
json.isNull --[[Kawaii]]
clear_tp_queue --[[Kawaii]]
get_script_bytecode --[[Eclipse]]
actor.get_actors --[[Trigon, VegaX, ArceusX V5, CodeX]]
__lime_base64decode --[[Lime]]
keytap --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
getcurrentactor --[[Kawaii, DeltaX]]
getrenv --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
isexecutorfunction --[[Lime]]
newcclosure --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
queue_on_tp --[[Kawaii]]
hasmetafield --[[Kawaii]]
get_signal_cons --[[Kawaii, DeltaX]]
RakNet.remove_send_hook --[[Kawaii]]
setscriptable --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Delta.roblox_version --[[DeltaX]]
lz4_decompress --[[DeltaX]]
mousescroll --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arcy.stop --[[ArceusX V5]]
replicatesignal --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.getprotos --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getproto --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
isrbxactive --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getdeletedactors --[[Kawaii, DeltaX]]
getstack --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
_G.clearScriptContainer --[[Trigon]]
arceus.makearceusfolder --[[Trigon]]
mousemoveabs --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
disableconnection --[[Trigon, VegaX, ArceusX V5, CodeX]]
base64decode --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arceus.isarceusfolder --[[Trigon]]
Drawing.Fonts --[[JadeX]]
ishooked --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
__lime_debug_getstack --[[Lime]]
consoleshow --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
iscclosure --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
IsKeyDown --[[Eclipse]]
readscript --[[Xinject]]
get_hidden_gui --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
iskeydown --[[Eclipse]]
DelFile --[[Eclipse]]
__lime_ws_poll --[[Lime]]
setstack --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
HttpGet --[[Xinject, Kawaii, Eclipse]]
readfileasync --[[Kawaii]]
getscriptglobals --[[Kawaii]]
sethiddenproperty --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
MakeWritable --[[Eclipse]]
syn.queue_on_teleport --[[Kawaii]]
imgui.setvsync --[[Kawaii]]
writecustomasset --[[FluxusZ]]
getgccache --[[FluxusZ]]
issynapsefunction --[[Trigon, VegaX, ArceusX V5, CodeX]]
getscriptfromthread --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setrenderproperty --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
is_eclipse_closure --[[Eclipse]]
actor.getactors --[[Trigon, VegaX, ArceusX V5, CodeX]]
syn.write_clipboard --[[Kawaii]]
getloadedmodules --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
SetConstant --[[Eclipse]]
gethiddenui --[[Kawaii, Eclipse]]
online_login --[[Xinject]]
iswaitingconnection --[[DeltaX]]
xi_setctx --[[Xinject]]
__kawaii_private_roots.ImGuiMethods.Separator --[[Kawaii]]
syn.crypt.decrypt --[[Kawaii]]
crypt.base64decode --[[Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.setstack --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
firetouchtransmitter --[[Kawaii]]
cleardrawcache --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
OpenXinject --[[Xinject]]
raknet.add_send_hook --[[Trigon, VegaX, ArceusX V5, CodeX]]
getprocessidentifier --[[Kawaii]]
fireserver --[[Xinject]]
writeinternal --[[Xinject]]
setclosureidentity --[[Trigon, VegaX, ArceusX V5, CodeX]]
arceus.WHWKIIIIWIIOSU --[[Trigon]]
WebSocket.Connect --[[Lime, FluxusZ, Eclipse]]
getfastflag --[[Kawaii]]
debug.profilebegin --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
Signal.new --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
loadfileasync --[[Kawaii]]
getfpscap --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getgamestate --[[Kawaii, DeltaX]]
islclosure --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
server.has_authority --[[DeltaX]]
isstackhidden --[[Kawaii]]
getscriptbytecode --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
detour_function --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
debug.getrawmetatable --[[Trigon, VegaX, ArceusX V5, CodeX]]
base64.encode --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setfpscap --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
Delta.architecture_str --[[DeltaX]]
is_executor_closure --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
json.escape --[[Kawaii]]
crypt.base64.decode --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getmenv --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
syn.crypt.custom.decrypt --[[Kawaii]]
getcallbackvalue --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
ArgumentFilter.new --[[Kawaii]]
firesignal --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
runAutoExec --[[Xinject]]
online_resume --[[Xinject]]
arceus.is_vng --[[Trigon]]
restoresignal --[[Trigon, VegaX, ArceusX V5, CodeX]]
isscriptable --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_ss_copy --[[Lime]]
on_actor_state_created.Connect --[[Kawaii]]
rconsolesettitle --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
hookmetamethod --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xinject.Settings.AddDropdown --[[Xinject]]
rLib.End --[[Xinject]]
Signal.Connect --[[Kawaii]]
bit.extract --[[Eclipse, DeltaX]]
voicechat.setmicmuted --[[Kawaii]]
xi_autoexec_mkdir --[[Xinject]]
is_krnl_closure --[[Trigon, VegaX, ArceusX V5, CodeX]]
raknet.remove_send_hook --[[ArceusX V5]]
Input.KeyPress --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.profileend --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
json.getpath --[[Kawaii]]
issignalhooked --[[Trigon, VegaX, ArceusX V5, CodeX]]
bit.badd --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
runautoexec --[[Xinject]]
ai_chat --[[Xinject]]
debug.setrawmetatable --[[Trigon, VegaX, ArceusX V5, CodeX]]
getsignalarguments --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
get_process_identifier --[[Kawaii]]
printidentity --[[Kawaii]]
setfastflag --[[Kawaii]]
DrawingImmediate.Line --[[Kawaii]]
syn.crypt.encrypt --[[Kawaii]]
actor.is_parallel --[[Trigon, VegaX, ArceusX V5, CodeX]]
getluastate --[[Kawaii, DeltaX]]
mouse2release --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
__lime_getreg --[[Lime]]
online_hastoken --[[Xinject]]
rconsoleinfo --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
consolewrite --[[Kawaii]]
Xinject.AISessions --[[Xinject]]
setidentity --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
appendfileasync --[[Kawaii]]
Drawing.new --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
set_clipboard --[[Eclipse, DeltaX]]
consoleinfo --[[Trigon, Xinject, VegaX, Kawaii, ArceusX V5, CodeX]]
__kawaii_private_roots.ImGuiMethods.ColorPicker --[[Kawaii]]
isfolder --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
queueteleport --[[Kawaii]]
crypt.hex_encode --[[FluxusZ]]
RakNet.Receive --[[Kawaii]]
iscustomcclosure --[[Kawaii, DeltaX]]
GetScripts --[[Xinject]]
voicechat.hasvoicechat --[[Kawaii]]
fire_click_detector --[[Eclipse]]
getreferencedby --[[Kawaii]]
syn.crypt.derive --[[Kawaii]]
__kawaii_private_roots.CloneGcPressure --[[Kawaii]]
getproperties --[[Kawaii, DeltaX]]
debug.getsafeenv --[[Kawaii]]
setinfo --[[Kawaii, ArceusX V5]]
__kawaii_private_roots.ImGuiMethods.Destroy --[[Kawaii]]
rconsoleclear --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
Duration.FromSeconds --[[DeltaX]]
consoleerr --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
replacefunc --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
ai_balance_req --[[Xinject]]
messagebox --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getsignals --[[Kawaii]]
MouseScroll --[[Eclipse]]
Regex.MatchMany --[[Kawaii]]
get_script_closure --[[Eclipse]]
Regex.new --[[Kawaii, DeltaX]]
__lime_httpget_bridge --[[Lime]]
new_c_closure --[[Eclipse]]
protectclosure --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.loadmodule --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
RakNet.OnPacketSend.Wait --[[Kawaii]]
__lime_base64encode --[[Lime]]
isfluxusfunction --[[Trigon, VegaX, ArceusX V5, CodeX]]
checkclosure --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xi_randbytes --[[Xinject]]
debug.getinfo --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
secure_call --[[Kawaii]]
get_actor_threads --[[Kawaii]]
NamecallFilter.new --[[Kawaii]]
rconsoletoggle --[[Kawaii]]
DrawingImmediate.Quad --[[Kawaii]]
openExternal --[[Xinject]]
RakNet.Enum.__tostring --[[Kawaii]]
arcy.learn --[[ArceusX V5]]
SaveScript --[[Xinject]]
WriteFile --[[Eclipse]]
keyclick --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
__kawaii_private_roots.FileDialogs.openfiledialog --[[Kawaii]]
arceus.WHWKIWIIOSU --[[Trigon]]
islocalsourcecontainer --[[Trigon, VegaX, ArceusX V5, CodeX]]
syn.secure_call --[[Kawaii]]
isprotohooked --[[Kawaii, DeltaX]]
ai_session_get --[[Xinject]]
getactorthreads --[[Kawaii]]
__lime_debug_getupvals --[[Lime]]
DrawingImmediate.FilledCircle --[[Kawaii]]
mouse2press --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
online_state --[[Xinject]]
Xinject.AISessionGet --[[Xinject]]
consoleclear --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getgc --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
ishiddenstack --[[Kawaii]]
_G.toggleMain --[[Trigon]]
rconsoleinputasync --[[Kawaii]]
xi_endexec --[[Xinject]]
get_properties --[[DeltaX]]
getprops --[[DeltaX]]
GetClipBoard --[[Eclipse]]
dofile --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
cache.cloneref --[[Trigon, VegaX, ArceusX V5, CodeX]]
IsFolder --[[Eclipse]]
Delta.architecture --[[DeltaX]]
ai_session_get_state --[[Xinject]]
__lime_ws_status --[[Lime]]
json.isObject --[[Kawaii]]
arceus.iscustomasset --[[Trigon]]
getsenv --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
isluaclosure --[[Kawaii]]
__lime_request_start --[[Lime]]
arcy.translate --[[ArceusX V5]]
debug.isuntouched --[[Kawaii]]
loginfo --[[Trigon, VegaX, ArceusX V5, CodeX]]
json.array --[[Kawaii]]
crypt.hash --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
protect --[[Xinject]]
report_event --[[Xinject]]
arceus.getmodificationtime --[[Trigon]]
Duration.FromDays --[[DeltaX]]
arceus.deletecustomasset --[[Trigon]]
debug.SetStack --[[Eclipse]]
toclipboard --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
fireremote --[[Xinject]]
DrawingImmediate.OutlinedText --[[Kawaii]]
xi_instdump --[[Xinject]]
decompile --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
clone_ref --[[Eclipse]]
split_locale --[[Xinject]]
setthreadidentity --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
bit.bswap --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
crypt.lz4.decompress --[[Kawaii]]
make_readonly --[[Lime, Trigon, VegaX, FluxusZ, Eclipse, ArceusX V5, DeltaX, CodeX]]
KeyPress --[[Eclipse]]
RakNet.OnPacketReceive.Connect --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.destroy --[[Kawaii]]
is_readonly --[[Kawaii]]
bit.tohex --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
dofileasync --[[Kawaii]]
mouse1click --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xi_decode --[[Xinject]]
RakNet.addreceivehook --[[Kawaii]]
json.values --[[Kawaii]]
setconnectionenabled --[[DeltaX]]
makereadonly --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
raknet.clear_all_send_hooks --[[Trigon, VegaX, ArceusX V5, CodeX]]
show_toast --[[ArceusX]]
Delta.get_platform --[[DeltaX]]
Delta.version_hash --[[DeltaX]]
protect_gui --[[Xinject, FluxusZ]]
glooperror --[[DeltaX]]
error --[[Kawaii]]
json.encode --[[Kawaii]]
getactorstates --[[Kawaii, DeltaX]]
Raknet.desync --[[DeltaX]]
getcbvalue --[[DeltaX]]
Duration.TimeSinceEpoch --[[DeltaX]]
Duration.FromYears --[[DeltaX]]
json.parse --[[Kawaii]]
MouseMoveAbs --[[Eclipse]]
isreadonly --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
SaveInstance --[[Kawaii]]
Duration.FromMilliseconds --[[DeltaX]]
GrantAccess --[[Xinject]]
pibble.is_pibble --[[DeltaX]]
writefile --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
base64_encode --[[Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
set_secure_instance --[[Trigon, VegaX, ArceusX V5, CodeX]]
httppost --[[DeltaX]]
bit.btest --[[Eclipse, DeltaX]]
zstd_compress --[[DeltaX]]
filtergc --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
clearqueue_on_teleport --[[DeltaX]]
lockassetsignal --[[Trigon, VegaX, ArceusX V5, CodeX]]
is_function_hooked --[[DeltaX]]
RakNet.Enum.__index --[[Kawaii]]
getconnectionfunction --[[DeltaX]]
getscriptclosure --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xi_queue_teleport --[[Xinject]]
LuaStateProxy.new --[[Kawaii, DeltaX]]
set_namecall_method --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, CodeX]]
rnet.desync --[[DeltaX]]
getthreadcaps --[[Kawaii]]
XINJECT_SEARCH.hub --[[Xinject]]
Xinject.AIChat --[[Xinject]]
get_nil_instances --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
setthreadcaps --[[Kawaii]]
comparefunction --[[Kawaii]]
set_raw_metatable --[[DeltaX]]
getmousepos --[[DeltaX]]
RakNet.OnPacketSend.Once --[[Kawaii]]
raknet.desync --[[DeltaX]]
DeltaSignal.new --[[DeltaX]]
is_parallel --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
info --[[Kawaii]]
RakNet.OnPacketReceive.connect --[[Kawaii]]
readbinarystringpropertyvalue --[[DeltaX]]
set_rbx_clipboard --[[DeltaX]]
emulate_call --[[Trigon, VegaX, ArceusX V5, CodeX]]
get_hidden_properties --[[DeltaX]]
getinstances --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
oth.get_original_thread --[[Kawaii, DeltaX]]
firetouchinterest --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
isdeltafunction --[[DeltaX]]
arceus.WHWKIIWIIOSU --[[Trigon]]
iselevatedthread --[[Lime]]
get_original_thread --[[DeltaX]]
get_renderstepped_list --[[DeltaX]]
arceus.openurl --[[Trigon]]
xi_beginexec --[[Xinject]]
getrenderstepcallbacks --[[DeltaX]]
debug.getproto --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
bit.arshift --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
gethiddenprops --[[DeltaX]]
syn.create_secure_function --[[Kawaii]]
readbspval --[[DeltaX]]
__lime_debug_getreg --[[Lime]]
isparallel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
queue_on_teleport --[[Lime, Trigon, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_modules --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.validlevel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
arcy.size --[[ArceusX V5]]
get_objects --[[Eclipse]]
arcy.open --[[ArceusX V5]]
NotFilter.new --[[Kawaii]]
_G.doget_indexed --[[FluxusZ]]
CallerFilter.new --[[Kawaii]]
validlevel --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
newlclosure --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
isexecutorthread --[[Kawaii, DeltaX]]
is_scriptable --[[Eclipse]]
crypt.zstd.compress --[[Kawaii]]
AnyFilter.new --[[Kawaii]]
is_c_closure --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
delinternal --[[Xinject]]
delfolder --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getgenv --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arceus.getversion --[[Trigon]]
__lime_request_poll --[[Lime]]
getuserdatatag --[[Eclipse]]
Duration.FromMonths --[[DeltaX]]
getscripthash --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xi_dbg --[[Xinject]]
getnil --[[Lime]]
getcallstack --[[Kawaii, ArceusX V5, DeltaX]]
set_thread_context --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
crypt.encrypt --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getmodules --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
Input.ScrollMouse --[[Trigon, VegaX, ArceusX V5, CodeX]]
http_request --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
searchTranslationVector --[[Xinject]]
set_scriptable --[[Eclipse]]
setnormalinstance --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.traceback --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
json.decode --[[Kawaii]]
__kawaii_private_roots.RuntimeView.loadstring --[[Kawaii]]
load --[[Eclipse]]
get_thread_context --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
RakNet.add_receive_hook --[[Kawaii]]
crypt.lz4decompress --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
hook_meta_method --[[Eclipse]]
GetUpvalue --[[Eclipse]]
Signal.Wait --[[Kawaii]]
cache.iscached --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
StartUp --[[Xinject]]
SetUpvalue --[[Eclipse]]
TypeFilter.new --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.InputText --[[Kawaii]]
get_script_from_thread --[[Eclipse]]
get_running_scripts --[[Eclipse]]
get_loaded_modules --[[Eclipse]]
get_gc_objects --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
sha256 --[[Xinject]]
syn.set_thread_identity --[[Kawaii]]
__lime_fab_install --[[Lime]]
gethiddenproperty --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_connections --[[Eclipse]]
xi_b64encode --[[Xinject]]
get_clip_board --[[Eclipse]]
DrawingImmediate.Circle --[[Kawaii]]
get_namecall_method --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
get_callback_value --[[Eclipse, DeltaX]]
isinternalfile --[[Xinject]]
xi_exec --[[Xinject]]
http.http_request --[[Eclipse]]
gettenv --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
sethiddenstack --[[Kawaii]]
__kawaii_private_roots.RuntimeView.printidentity --[[Kawaii]]
oth.hook --[[Kawaii, DeltaX]]
Duration.FromHours --[[DeltaX]]
voicechat.unpause --[[Kawaii]]
crypt.hex_decode --[[FluxusZ]]
consolename --[[Kawaii]]
hookproto --[[Kawaii, DeltaX]]
fire_proximity_prompt --[[Eclipse]]
queueonteleport --[[Trigon, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.SetConstant --[[Eclipse]]
clear_drawing_lib --[[Eclipse]]
runonactor --[[Kawaii, DeltaX]]
debug.GetUpvalue --[[Eclipse]]
iswritable --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
debug.GetStack --[[Eclipse]]
makefolder --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.GetRegistry --[[Eclipse]]
printuiwarn --[[Trigon, VegaX, ArceusX V5, CodeX]]
RakNet.desync --[[DeltaX]]
LoadFile --[[Eclipse]]
UserdataTypeFilter.new --[[Kawaii]]
debug.GetConstants --[[Eclipse]]
clone_reference --[[Eclipse]]
crypt.decode --[[Xinject]]
bit.rrotate --[[Eclipse, DeltaX]]
getidentity --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setsecureinstance --[[Trigon, VegaX, ArceusX V5, CodeX]]
bit.lrotate --[[Eclipse, DeltaX]]
raknet.receive --[[Trigon, VegaX, ArceusX V5, CodeX]]
getrenderproperty --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
printuierror --[[Trigon, VegaX, ArceusX V5, CodeX]]
checkparallel --[[Kawaii, DeltaX]]
Input.MoveMouse --[[Trigon, VegaX, ArceusX V5, CodeX]]
consoledestroy --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
arceus.SDKEUIEWOWOASKS --[[Trigon]]
syn.unprotect_gui --[[Kawaii]]
debug.getcallstack --[[Kawaii, ArceusX V5, DeltaX]]
isgameactive --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
SetStack --[[Eclipse]]
debug.setmetatable --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
bit.ror --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
__cx_set_rbxids --[[Lime]]
ReadFile --[[Eclipse]]
base64_decode --[[Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
xinject.Settings.AddInput --[[Xinject]]
Drawing.cleardrawcache --[[Eclipse]]
RakNet.OnPacketSend.connect --[[Kawaii]]
Duration.FromMinutes --[[DeltaX]]
createsecurefolder --[[Trigon, VegaX, ArceusX V5, CodeX]]
MouseMoveABS --[[Eclipse]]
set_thread_identity --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
KeyRelease --[[Eclipse]]
game.HttpPost --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
signal.new --[[Trigon, VegaX, ArceusX V5, CodeX]]
json.tryDecode --[[Kawaii]]
__lime_int_asset --[[Lime]]
isfunctionhooked --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
HookMetaMethod --[[Eclipse]]
GetUpvalues --[[Eclipse]]
GetStack --[[Eclipse]]
GetProtos --[[Eclipse]]
crypt.hex.encode --[[FluxusZ]]
setproximitypromptduration --[[Kawaii, DeltaX]]
GetInfo --[[Eclipse]]
mousemoverel --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
GetConstants --[[Eclipse]]
getproximitypromptduration --[[Kawaii, DeltaX]]
MouseMove --[[Eclipse]]
GetConstant --[[Eclipse]]
getprotos --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setrawmetatable --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
DoFile --[[Eclipse]]
get_actors --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
__kawaii_private_roots.FileDialogBridge --[[Kawaii]]
syn.cache_replace --[[Kawaii]]
__kawaii_private_roots.InstanceCloneProxyFactory --[[Kawaii]]
arcy.play --[[ArceusX V5]]
rconsoletop --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.SliderFloat --[[Kawaii]]
cloneref --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_user_data_tag --[[Eclipse]]
base64.decode --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arceus.retrievecustomasset --[[Trigon]]
hookfunction --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
get_thread_identity --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getrunningscripts --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.getupvalue --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__kawaii_private_roots.FileDialogs.savefiledialog --[[Kawaii]]
__kawaii_private_roots.FileDialogs.openfilesdialog --[[Kawaii]]
openfolderdialog --[[FluxusZ, Kawaii]]
to_clipboard --[[Eclipse]]
__lime_debug_setstack --[[Lime]]
__kawaii_private_roots.HttpPost --[[Kawaii]]
__kawaii_private_roots.FileDialogObjectBridge --[[Kawaii]]
consolesettitle --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
Raknet.is_enabled --[[DeltaX]]
identifyexecutor --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_identifyexec --[[Lime]]
queueontp --[[Kawaii]]
isgamescriptconnection --[[DeltaX]]
bit.band --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
voicechat.joincomchannel --[[Kawaii]]
arceus.isarceusfile --[[Trigon]]
getinfo --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getactorfromthread --[[Kawaii]]
DrawingImmediate.FilledTriangle --[[Kawaii]]
create_secure_folder --[[Trigon, VegaX, ArceusX V5, CodeX]]
getcaller --[[Trigon, VegaX, ArceusX V5, CodeX]]
DrawFont.Register --[[Kawaii]]
getscripts --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
debug.GetProto --[[Eclipse]]
DrawingImmediate.FilledQuad --[[Kawaii]]
debug.info --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
report_error --[[Xinject]]
DrawingImmediate.Triangle --[[Kawaii]]
getrendersteppedlist --[[Kawaii, ArceusX V5, DeltaX]]
keypress --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setclipboard --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getscriptsthatrun --[[DeltaX]]
arceus.encrypted --[[Trigon]]
getupvalues --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
_G.xconsole --[[Xinject]]
restoreproto --[[Kawaii, DeltaX]]
syn.crypt.hash --[[Kawaii]]
compareinstances --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arceus.WHWKIIIWIIOSU --[[Trigon]]
__lime_noop --[[Lime]]
raknet.is_enabled --[[ArceusX V5, DeltaX]]
getfunctionhash --[[Lime, Trigon, JadeX, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
delfile --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getinstancesbyclass --[[Kawaii]]
syn.secrun --[[Kawaii]]
os.clock --[[Xinject]]
is_l_closure --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
xi_hash --[[Xinject]]
debug.dumpcodesize --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
isourthread --[[Kawaii, DeltaX]]
bit.bmul --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
__lime_conn_flags --[[Lime]]
syn.crypt.custom.hash --[[Kawaii]]
arceus.writecustomasset --[[Trigon]]
syn.protect_gui --[[Kawaii]]
getcallbackmember --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
warnuiconsole --[[Trigon, VegaX, ArceusX V5, CodeX]]
uienv --[[Xinject]]
arceus.listarceusfiles --[[Trigon]]
voicechat.pause --[[Kawaii]]
RakNet.add_send_hook --[[Kawaii]]
debug.dumpheap --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
getconnections --[[Lime, Trigon, JadeX, Xinject, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setclosurecaps --[[Trigon, VegaX, ArceusX V5, CodeX]]
trampoline_call --[[Kawaii]]
lz4.compress --[[Kawaii]]
crypt.lz4compress --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
lz4.decompress --[[Kawaii]]
json.quote --[[Kawaii]]
bytecode_to_lua --[[Kawaii]]
arceus.deletearceusfile --[[Trigon]]
RakNet.removereceivehook --[[Kawaii]]
setsimulationradius --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
rconsolehidden --[[Kawaii]]
sethiddenprop --[[Kawaii, DeltaX]]
XOS._build --[[Xinject]]
getsimulationradius --[[Kawaii, DeltaX]]
filter_gc --[[Trigon, VegaX, Eclipse, ArceusX V5, CodeX]]
getmetafield --[[Kawaii]]
json.type --[[Kawaii]]
__kawaii_private_roots.ImGuiMethods.Text --[[Kawaii]]
saveinstance --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
restorefunc --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
crypt.generatekey --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
disassemble --[[Kawaii]]
getexecutorversion --[[Kawaii]]
gethwid --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
getfastflagtype --[[Kawaii]]
unprotect_gui --[[Xinject, FluxusZ]]
isnetworkowner --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
debug.getstack --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
RakNet.is_enabled --[[Kawaii, DeltaX]]
mouse1press --[[Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
AllFilter.new --[[Kawaii]]
xi_autoexec_list --[[Xinject]]
issecuredinstance --[[Trigon, VegaX, ArceusX V5, CodeX]]
getinstancecache --[[Kawaii, DeltaX]]
xi_capturectx --[[Xinject]]
get_current_actor --[[Kawaii, DeltaX]]
setnamecallmethod --[[Lime, Trigon, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
isexploitfunction --[[Kawaii]]
json.unescape --[[Kawaii]]
rconsoletopmost --[[Kawaii]]
run_on_thread --[[Kawaii]]
__lime_int_readfile --[[Lime]]
_G.load_rs_scripts --[[Trigon]]
json.stringify --[[Kawaii]]
arceus.EOWOWQPQPPALSKSNX --[[Trigon]]
json.pretty --[[Kawaii]]
getcustomasset --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
replaceclosure --[[Lime, Trigon, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getnamecallmethod --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
bit.countrz --[[Eclipse, DeltaX]]
logerror --[[Trigon, VegaX, ArceusX V5, CodeX]]
getscriptcaller --[[Trigon, VegaX, ArceusX V5, CodeX]]
raknet.send --[[Trigon, VegaX, ArceusX V5, CodeX]]
json.encodePretty --[[Kawaii]]
json.isArray --[[Kawaii]]
json.keys --[[Kawaii]]
get_script_function --[[Trigon, VegaX, Eclipse, ArceusX V5, CodeX]]
__lime_int_listfiles --[[Lime]]
xi_clearctx --[[Xinject]]
consoleinput --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
mouse2click --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
Xinject.OnlineLogin --[[Xinject]]
ArgCountFilter.new --[[Kawaii]]
json.object --[[Kawaii]]
deletefolder --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
Input.RightClick --[[Trigon, VegaX, ArceusX V5, CodeX]]
checkkey --[[Xinject]]
is_protosmasher_closure --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.dumprefs --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
erroruiconsole --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.setconstant --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
arceus.getfilesize --[[Trigon]]
is_our_closure --[[Trigon, VegaX, ArceusX V5, DeltaX, CodeX]]
DelScript --[[Xinject]]
getscriptfunction --[[Lime, Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
syn.cache_invalidate --[[Kawaii]]
logprint --[[Trigon, VegaX, ArceusX V5, CodeX]]
debug.getconstants --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
crypt_base64encode --[[Lime]]
Signal.Once --[[Kawaii]]
bit.bsub --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
bit.bdiv --[[Trigon, VegaX, Kawaii, ArceusX V5, CodeX]]
executeclipboard --[[Trigon, Xinject, VegaX, ArceusX V5, CodeX]]
arceus.WOWPALAKSZMNXBRU --[[Trigon]]
make_writeable --[[Lime, Trigon, VegaX, FluxusZ, ArceusX V5, DeltaX, CodeX]]
hex.encode --[[FluxusZ]]
isfluxusclosure --[[Trigon, VegaX, ArceusX V5, CodeX]]
__lime_empty_fn --[[Lime]]
report_bytecode --[[Xinject]]
debug.getmemorycategory --[[Trigon, VegaX, Eclipse, ArceusX V5, DeltaX, CodeX]]
isnewcclosure --[[Lime, Kawaii, DeltaX]]
__kawaii_private_roots.HttpGet --[[Kawaii]]
xi_pcall --[[Xinject]]
getcurrentline --[[Trigon, VegaX, ArceusX V5, CodeX]]
Xinject.OnlineServiceLogin --[[Xinject]]
XOS.open --[[Xinject]]
debug.getconstant --[[Lime, Trigon, JadeX, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getrenvglobal --[[Trigon, VegaX, ArceusX V5, CodeX]]
isinternal --[[Xinject]]
clonefunction --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
setcontext --[[Trigon, VegaX, ArceusX V5, CodeX]]
httpget --[[Xinject, Kawaii, DeltaX]]
listscripts --[[Xinject]]
setrbxclipboard --[[Lime, Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
rconsoleinput --[[Trigon, Xinject, VegaX, FluxusZ, Kawaii, ArceusX V5, DeltaX, CodeX]]
isfile --[[Lime, Trigon, JadeX, Xinject, VegaX, FluxusZ, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
getcontext --[[Trigon, VegaX, ArceusX V5, CodeX]]
syn_backup.request --[[Xinject]]
arceus.ispermissiongranted --[[Trigon]]
messageboxasync --[[Kawaii]]
clearteleportqueue --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
getsignalwhitelist --[[Trigon, VegaX, Kawaii, ArceusX V5, DeltaX, CodeX]]
makewriteable --[[Trigon, VegaX, FluxusZ, Kawaii, ArceusX V5, CodeX]]
bit.lshift --[[Trigon, VegaX, Kawaii, Eclipse, ArceusX V5, DeltaX, CodeX]]
__lime_caps_probe --[[Lime]]
